# ---- Build Stage ----
FROM node:22 AS build

# Set the working directory
WORKDIR /app

# Copy package files first (leveraging Docker caching)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application files
COPY . .

# Build arguments - Setup
ARG VITE_BACKEND_URL
ARG VITE_PROCORE_BASE_URL
ARG VITE_ENVIRONMENT

# Build arguments - Stripe Products
ARG VITE_STRIPE_PRODUCT_ID_EARLY_ADOPTER
ARG VITE_STRIPE_PRODUCT_ID_STANDARD
ARG VITE_STRIPE_PRODUCT_ID_PROFESSIONAL
ARG VITE_STRIPE_PRODUCT_ID_BUSINESS

# Build arguments - Stripe Prices
ARG VITE_STRIPE_PRICE_STANDARD_MONTHLY
ARG VITE_STRIPE_PRICE_STANDARD_ANNUAL
ARG VITE_STRIPE_PRICE_PROFESSIONAL_MONTHLY
ARG VITE_STRIPE_PRICE_PROFESSIONAL_ANNUAL
ARG VITE_STRIPE_PRICE_BUSINESS_MONTHLY
ARG VITE_STRIPE_PRICE_BUSINESS_ANNUAL
ARG VITE_STRIPE_STORAGE_ADDON_PRICE

# Create .env file and build static files
# Sensitive values (API key, Rollbar token) are mounted as BuildKit secrets
# to keep them out of image layer history
RUN --mount=type=secret,id=VITE_TALIHO_API_KEY \
    --mount=type=secret,id=VITE_ROLLBAR_ACCESS_TOKEN \
    <<EOF
cat > .env <<ENVFILE
VITE_BACKEND_URL=$VITE_BACKEND_URL
VITE_PROCORE_BASE_URL=$VITE_PROCORE_BASE_URL
VITE_ROLLBAR_ACCESS_TOKEN=$(cat /run/secrets/VITE_ROLLBAR_ACCESS_TOKEN)
VITE_ENVIRONMENT=$VITE_ENVIRONMENT
VITE_TALIHO_API_KEY=$(cat /run/secrets/VITE_TALIHO_API_KEY)
VITE_STRIPE_PRODUCT_ID_EARLY_ADOPTER=$VITE_STRIPE_PRODUCT_ID_EARLY_ADOPTER
VITE_STRIPE_PRODUCT_ID_STANDARD=$VITE_STRIPE_PRODUCT_ID_STANDARD
VITE_STRIPE_PRODUCT_ID_PROFESSIONAL=$VITE_STRIPE_PRODUCT_ID_PROFESSIONAL
VITE_STRIPE_PRODUCT_ID_BUSINESS=$VITE_STRIPE_PRODUCT_ID_BUSINESS
VITE_STRIPE_PRICE_STANDARD_MONTHLY=$VITE_STRIPE_PRICE_STANDARD_MONTHLY
VITE_STRIPE_PRICE_STANDARD_ANNUAL=$VITE_STRIPE_PRICE_STANDARD_ANNUAL
VITE_STRIPE_PRICE_PROFESSIONAL_MONTHLY=$VITE_STRIPE_PRICE_PROFESSIONAL_MONTHLY
VITE_STRIPE_PRICE_PROFESSIONAL_ANNUAL=$VITE_STRIPE_PRICE_PROFESSIONAL_ANNUAL
VITE_STRIPE_PRICE_BUSINESS_MONTHLY=$VITE_STRIPE_PRICE_BUSINESS_MONTHLY
VITE_STRIPE_PRICE_BUSINESS_ANNUAL=$VITE_STRIPE_PRICE_BUSINESS_ANNUAL
VITE_STRIPE_STORAGE_ADDON_PRICE=$VITE_STRIPE_STORAGE_ADDON_PRICE
ENVFILE
npm run build
EOF

# ---- Nginx Stage ----
FROM nginx:alpine AS production

# Remove default Nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy built files from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom Nginx config
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose port 3000
EXPOSE 3000

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]