/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScannedQRImport } from './routes/scannedQR'
import { Route as LoggedImport } from './routes/logged'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as TaskSignoffWorkflowIdImport } from './routes/task-signoff.$workflowId'
import { Route as QrcodeQrcodeIdImport } from './routes/qrcode.$qrcodeId'
import { Route as ProjectProjectIdImport } from './routes/project.$projectId'
import { Route as ProcoreSelectCompanyImport } from './routes/procore/select-company'
import { Route as ProcoreOauthSuccessImport } from './routes/procore/oauth-success'
import { Route as ProcoreOauthErrorImport } from './routes/procore/oauth-error'
import { Route as ProcoreFetchImport } from './routes/procore/fetch'
import { Route as GroupGroupIdImport } from './routes/group.$groupId'
import { Route as BallInCourtWorkflowIdImport } from './routes/ball-in-court.$workflowId'
import { Route as AdminCustomersImport } from './routes/admin.customers'
import { Route as ToolsToolItemIdImport } from './routes/tools.$tool.$itemId'
import { Route as OauthProcoreLoginImport } from './routes/oauth/procore/login'
import { Route as OauthProcoreCallbackImport } from './routes/oauth/procore/callback'
import { Route as NfcV1NfcIdImport } from './routes/nfc.v1.$nfcId'

// Create Virtual Routes

const VerifyEmailLazyImport = createFileRoute('/verify-email')()
const SignupLazyImport = createFileRoute('/signup')()
const SettingsLazyImport = createFileRoute('/settings')()
const SampleLazyImport = createFileRoute('/sample')()
const ProjectsLazyImport = createFileRoute('/projects')()
const MyQrcodesLazyImport = createFileRoute('/my-qrcodes')()
const GroupsLazyImport = createFileRoute('/groups')()
const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const CreateQrLazyImport = createFileRoute('/create-qr')()
const CheckoutLazyImport = createFileRoute('/checkout')()
const VerifyEmailTokenLazyImport = createFileRoute('/verify-email/$token')()
const StorageSuccessLazyImport = createFileRoute('/storage/success')()
const AdminStatsLazyImport = createFileRoute('/admin/stats')()
const AdminOnlineLazyImport = createFileRoute('/admin/online')()
const AdminNfcLazyImport = createFileRoute('/admin/nfc')()
const AdminGhlLazyImport = createFileRoute('/admin/ghl')()
const AdminDbBackfillLazyImport = createFileRoute('/admin/db-backfill')()
const AdminCustomersIndexLazyImport = createFileRoute('/admin/customers/')()
const AdminCustomersCompanyIdLazyImport = createFileRoute(
  '/admin/customers/$companyId',
)()

// Create/Update Routes

const VerifyEmailLazyRoute = VerifyEmailLazyImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/verify-email.lazy').then((d) => d.Route))

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const SampleLazyRoute = SampleLazyImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sample.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const MyQrcodesLazyRoute = MyQrcodesLazyImport.update({
  id: '/my-qrcodes',
  path: '/my-qrcodes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/my-qrcodes.lazy').then((d) => d.Route))

const GroupsLazyRoute = GroupsLazyImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/groups.lazy').then((d) => d.Route))

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const CreateQrLazyRoute = CreateQrLazyImport.update({
  id: '/create-qr',
  path: '/create-qr',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create-qr.lazy').then((d) => d.Route))

const CheckoutLazyRoute = CheckoutLazyImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/checkout.lazy').then((d) => d.Route))

const ScannedQRRoute = ScannedQRImport.update({
  id: '/scannedQR',
  path: '/scannedQR',
  getParentRoute: () => rootRoute,
} as any)

const LoggedRoute = LoggedImport.update({
  id: '/logged',
  path: '/logged',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailTokenLazyRoute = VerifyEmailTokenLazyImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => VerifyEmailLazyRoute,
} as any).lazy(() =>
  import('./routes/verify-email.$token.lazy').then((d) => d.Route),
)

const StorageSuccessLazyRoute = StorageSuccessLazyImport.update({
  id: '/storage/success',
  path: '/storage/success',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/storage.success.lazy').then((d) => d.Route),
)

const AdminStatsLazyRoute = AdminStatsLazyImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.stats.lazy').then((d) => d.Route))

const AdminOnlineLazyRoute = AdminOnlineLazyImport.update({
  id: '/admin/online',
  path: '/admin/online',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.online.lazy').then((d) => d.Route))

const AdminNfcLazyRoute = AdminNfcLazyImport.update({
  id: '/admin/nfc',
  path: '/admin/nfc',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.nfc.lazy').then((d) => d.Route))

const AdminGhlLazyRoute = AdminGhlLazyImport.update({
  id: '/admin/ghl',
  path: '/admin/ghl',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.ghl.lazy').then((d) => d.Route))

const AdminDbBackfillLazyRoute = AdminDbBackfillLazyImport.update({
  id: '/admin/db-backfill',
  path: '/admin/db-backfill',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin.db-backfill.lazy').then((d) => d.Route),
)

const TaskSignoffWorkflowIdRoute = TaskSignoffWorkflowIdImport.update({
  id: '/task-signoff/$workflowId',
  path: '/task-signoff/$workflowId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/task-signoff.$workflowId.lazy').then((d) => d.Route),
)

const QrcodeQrcodeIdRoute = QrcodeQrcodeIdImport.update({
  id: '/qrcode/$qrcodeId',
  path: '/qrcode/$qrcodeId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdRoute = ProjectProjectIdImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProcoreSelectCompanyRoute = ProcoreSelectCompanyImport.update({
  id: '/procore/select-company',
  path: '/procore/select-company',
  getParentRoute: () => rootRoute,
} as any)

const ProcoreOauthSuccessRoute = ProcoreOauthSuccessImport.update({
  id: '/procore/oauth-success',
  path: '/procore/oauth-success',
  getParentRoute: () => rootRoute,
} as any)

const ProcoreOauthErrorRoute = ProcoreOauthErrorImport.update({
  id: '/procore/oauth-error',
  path: '/procore/oauth-error',
  getParentRoute: () => rootRoute,
} as any)

const ProcoreFetchRoute = ProcoreFetchImport.update({
  id: '/procore/fetch',
  path: '/procore/fetch',
  getParentRoute: () => rootRoute,
} as any)

const GroupGroupIdRoute = GroupGroupIdImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRoute,
} as any)

const BallInCourtWorkflowIdRoute = BallInCourtWorkflowIdImport.update({
  id: '/ball-in-court/$workflowId',
  path: '/ball-in-court/$workflowId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/ball-in-court.$workflowId.lazy').then((d) => d.Route),
)

const AdminCustomersRoute = AdminCustomersImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRoute,
} as any)

const AdminCustomersIndexLazyRoute = AdminCustomersIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any).lazy(() =>
  import('./routes/admin.customers.index.lazy').then((d) => d.Route),
)

const AdminCustomersCompanyIdLazyRoute =
  AdminCustomersCompanyIdLazyImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AdminCustomersRoute,
  } as any).lazy(() =>
    import('./routes/admin.customers.$companyId.lazy').then((d) => d.Route),
  )

const ToolsToolItemIdRoute = ToolsToolItemIdImport.update({
  id: '/tools/$tool/$itemId',
  path: '/tools/$tool/$itemId',
  getParentRoute: () => rootRoute,
} as any)

const OauthProcoreLoginRoute = OauthProcoreLoginImport.update({
  id: '/oauth/procore/login',
  path: '/oauth/procore/login',
  getParentRoute: () => rootRoute,
} as any)

const OauthProcoreCallbackRoute = OauthProcoreCallbackImport.update({
  id: '/oauth/procore/callback',
  path: '/oauth/procore/callback',
  getParentRoute: () => rootRoute,
} as any)

const NfcV1NfcIdRoute = NfcV1NfcIdImport.update({
  id: '/nfc/v1/$nfcId',
  path: '/nfc/v1/$nfcId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/logged': {
      id: '/logged'
      path: '/logged'
      fullPath: '/logged'
      preLoaderRoute: typeof LoggedImport
      parentRoute: typeof rootRoute
    }
    '/scannedQR': {
      id: '/scannedQR'
      path: '/scannedQR'
      fullPath: '/scannedQR'
      preLoaderRoute: typeof ScannedQRImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-qr': {
      id: '/create-qr'
      path: '/create-qr'
      fullPath: '/create-qr'
      preLoaderRoute: typeof CreateQrLazyImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsLazyImport
      parentRoute: typeof rootRoute
    }
    '/my-qrcodes': {
      id: '/my-qrcodes'
      path: '/my-qrcodes'
      fullPath: '/my-qrcodes'
      preLoaderRoute: typeof MyQrcodesLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersImport
      parentRoute: typeof rootRoute
    }
    '/ball-in-court/$workflowId': {
      id: '/ball-in-court/$workflowId'
      path: '/ball-in-court/$workflowId'
      fullPath: '/ball-in-court/$workflowId'
      preLoaderRoute: typeof BallInCourtWorkflowIdImport
      parentRoute: typeof rootRoute
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/procore/fetch': {
      id: '/procore/fetch'
      path: '/procore/fetch'
      fullPath: '/procore/fetch'
      preLoaderRoute: typeof ProcoreFetchImport
      parentRoute: typeof rootRoute
    }
    '/procore/oauth-error': {
      id: '/procore/oauth-error'
      path: '/procore/oauth-error'
      fullPath: '/procore/oauth-error'
      preLoaderRoute: typeof ProcoreOauthErrorImport
      parentRoute: typeof rootRoute
    }
    '/procore/oauth-success': {
      id: '/procore/oauth-success'
      path: '/procore/oauth-success'
      fullPath: '/procore/oauth-success'
      preLoaderRoute: typeof ProcoreOauthSuccessImport
      parentRoute: typeof rootRoute
    }
    '/procore/select-company': {
      id: '/procore/select-company'
      path: '/procore/select-company'
      fullPath: '/procore/select-company'
      preLoaderRoute: typeof ProcoreSelectCompanyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/qrcode/$qrcodeId': {
      id: '/qrcode/$qrcodeId'
      path: '/qrcode/$qrcodeId'
      fullPath: '/qrcode/$qrcodeId'
      preLoaderRoute: typeof QrcodeQrcodeIdImport
      parentRoute: typeof rootRoute
    }
    '/task-signoff/$workflowId': {
      id: '/task-signoff/$workflowId'
      path: '/task-signoff/$workflowId'
      fullPath: '/task-signoff/$workflowId'
      preLoaderRoute: typeof TaskSignoffWorkflowIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/db-backfill': {
      id: '/admin/db-backfill'
      path: '/admin/db-backfill'
      fullPath: '/admin/db-backfill'
      preLoaderRoute: typeof AdminDbBackfillLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/ghl': {
      id: '/admin/ghl'
      path: '/admin/ghl'
      fullPath: '/admin/ghl'
      preLoaderRoute: typeof AdminGhlLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/nfc': {
      id: '/admin/nfc'
      path: '/admin/nfc'
      fullPath: '/admin/nfc'
      preLoaderRoute: typeof AdminNfcLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/online': {
      id: '/admin/online'
      path: '/admin/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AdminOnlineLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/storage/success': {
      id: '/storage/success'
      path: '/storage/success'
      fullPath: '/storage/success'
      preLoaderRoute: typeof StorageSuccessLazyImport
      parentRoute: typeof rootRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenLazyImport
      parentRoute: typeof VerifyEmailLazyImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/nfc/v1/$nfcId': {
      id: '/nfc/v1/$nfcId'
      path: '/nfc/v1/$nfcId'
      fullPath: '/nfc/v1/$nfcId'
      preLoaderRoute: typeof NfcV1NfcIdImport
      parentRoute: typeof rootRoute
    }
    '/oauth/procore/callback': {
      id: '/oauth/procore/callback'
      path: '/oauth/procore/callback'
      fullPath: '/oauth/procore/callback'
      preLoaderRoute: typeof OauthProcoreCallbackImport
      parentRoute: typeof rootRoute
    }
    '/oauth/procore/login': {
      id: '/oauth/procore/login'
      path: '/oauth/procore/login'
      fullPath: '/oauth/procore/login'
      preLoaderRoute: typeof OauthProcoreLoginImport
      parentRoute: typeof rootRoute
    }
    '/tools/$tool/$itemId': {
      id: '/tools/$tool/$itemId'
      path: '/tools/$tool/$itemId'
      fullPath: '/tools/$tool/$itemId'
      preLoaderRoute: typeof ToolsToolItemIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/customers/$companyId': {
      id: '/admin/customers/$companyId'
      path: '/$companyId'
      fullPath: '/admin/customers/$companyId'
      preLoaderRoute: typeof AdminCustomersCompanyIdLazyImport
      parentRoute: typeof AdminCustomersImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexLazyImport
      parentRoute: typeof AdminCustomersImport
    }
  }
}

// Create and export the route tree

interface VerifyEmailLazyRouteChildren {
  VerifyEmailTokenLazyRoute: typeof VerifyEmailTokenLazyRoute
}

const VerifyEmailLazyRouteChildren: VerifyEmailLazyRouteChildren = {
  VerifyEmailTokenLazyRoute: VerifyEmailTokenLazyRoute,
}

const VerifyEmailLazyRouteWithChildren = VerifyEmailLazyRoute._addFileChildren(
  VerifyEmailLazyRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersCompanyIdLazyRoute: typeof AdminCustomersCompanyIdLazyRoute
  AdminCustomersIndexLazyRoute: typeof AdminCustomersIndexLazyRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCompanyIdLazyRoute: AdminCustomersCompanyIdLazyRoute,
  AdminCustomersIndexLazyRoute: AdminCustomersIndexLazyRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logged': typeof LoggedRoute
  '/scannedQR': typeof ScannedQRRoute
  '/checkout': typeof CheckoutLazyRoute
  '/create-qr': typeof CreateQrLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/groups': typeof GroupsLazyRoute
  '/my-qrcodes': typeof MyQrcodesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/sample': typeof SampleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signup': typeof SignupLazyRoute
  '/verify-email': typeof VerifyEmailLazyRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/ball-in-court/$workflowId': typeof BallInCourtWorkflowIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/procore/fetch': typeof ProcoreFetchRoute
  '/procore/oauth-error': typeof ProcoreOauthErrorRoute
  '/procore/oauth-success': typeof ProcoreOauthSuccessRoute
  '/procore/select-company': typeof ProcoreSelectCompanyRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/qrcode/$qrcodeId': typeof QrcodeQrcodeIdRoute
  '/task-signoff/$workflowId': typeof TaskSignoffWorkflowIdRoute
  '/admin/db-backfill': typeof AdminDbBackfillLazyRoute
  '/admin/ghl': typeof AdminGhlLazyRoute
  '/admin/nfc': typeof AdminNfcLazyRoute
  '/admin/online': typeof AdminOnlineLazyRoute
  '/admin/stats': typeof AdminStatsLazyRoute
  '/storage/success': typeof StorageSuccessLazyRoute
  '/verify-email/$token': typeof VerifyEmailTokenLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/nfc/v1/$nfcId': typeof NfcV1NfcIdRoute
  '/oauth/procore/callback': typeof OauthProcoreCallbackRoute
  '/oauth/procore/login': typeof OauthProcoreLoginRoute
  '/tools/$tool/$itemId': typeof ToolsToolItemIdRoute
  '/admin/customers/$companyId': typeof AdminCustomersCompanyIdLazyRoute
  '/admin/customers/': typeof AdminCustomersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logged': typeof LoggedRoute
  '/scannedQR': typeof ScannedQRRoute
  '/checkout': typeof CheckoutLazyRoute
  '/create-qr': typeof CreateQrLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/groups': typeof GroupsLazyRoute
  '/my-qrcodes': typeof MyQrcodesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/sample': typeof SampleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signup': typeof SignupLazyRoute
  '/verify-email': typeof VerifyEmailLazyRouteWithChildren
  '/ball-in-court/$workflowId': typeof BallInCourtWorkflowIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/procore/fetch': typeof ProcoreFetchRoute
  '/procore/oauth-error': typeof ProcoreOauthErrorRoute
  '/procore/oauth-success': typeof ProcoreOauthSuccessRoute
  '/procore/select-company': typeof ProcoreSelectCompanyRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/qrcode/$qrcodeId': typeof QrcodeQrcodeIdRoute
  '/task-signoff/$workflowId': typeof TaskSignoffWorkflowIdRoute
  '/admin/db-backfill': typeof AdminDbBackfillLazyRoute
  '/admin/ghl': typeof AdminGhlLazyRoute
  '/admin/nfc': typeof AdminNfcLazyRoute
  '/admin/online': typeof AdminOnlineLazyRoute
  '/admin/stats': typeof AdminStatsLazyRoute
  '/storage/success': typeof StorageSuccessLazyRoute
  '/verify-email/$token': typeof VerifyEmailTokenLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/nfc/v1/$nfcId': typeof NfcV1NfcIdRoute
  '/oauth/procore/callback': typeof OauthProcoreCallbackRoute
  '/oauth/procore/login': typeof OauthProcoreLoginRoute
  '/tools/$tool/$itemId': typeof ToolsToolItemIdRoute
  '/admin/customers/$companyId': typeof AdminCustomersCompanyIdLazyRoute
  '/admin/customers': typeof AdminCustomersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/logged': typeof LoggedRoute
  '/scannedQR': typeof ScannedQRRoute
  '/checkout': typeof CheckoutLazyRoute
  '/create-qr': typeof CreateQrLazyRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/groups': typeof GroupsLazyRoute
  '/my-qrcodes': typeof MyQrcodesLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/sample': typeof SampleLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/signup': typeof SignupLazyRoute
  '/verify-email': typeof VerifyEmailLazyRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/ball-in-court/$workflowId': typeof BallInCourtWorkflowIdRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/procore/fetch': typeof ProcoreFetchRoute
  '/procore/oauth-error': typeof ProcoreOauthErrorRoute
  '/procore/oauth-success': typeof ProcoreOauthSuccessRoute
  '/procore/select-company': typeof ProcoreSelectCompanyRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/qrcode/$qrcodeId': typeof QrcodeQrcodeIdRoute
  '/task-signoff/$workflowId': typeof TaskSignoffWorkflowIdRoute
  '/admin/db-backfill': typeof AdminDbBackfillLazyRoute
  '/admin/ghl': typeof AdminGhlLazyRoute
  '/admin/nfc': typeof AdminNfcLazyRoute
  '/admin/online': typeof AdminOnlineLazyRoute
  '/admin/stats': typeof AdminStatsLazyRoute
  '/storage/success': typeof StorageSuccessLazyRoute
  '/verify-email/$token': typeof VerifyEmailTokenLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/nfc/v1/$nfcId': typeof NfcV1NfcIdRoute
  '/oauth/procore/callback': typeof OauthProcoreCallbackRoute
  '/oauth/procore/login': typeof OauthProcoreLoginRoute
  '/tools/$tool/$itemId': typeof ToolsToolItemIdRoute
  '/admin/customers/$companyId': typeof AdminCustomersCompanyIdLazyRoute
  '/admin/customers/': typeof AdminCustomersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logged'
    | '/scannedQR'
    | '/checkout'
    | '/create-qr'
    | '/forgot-password'
    | '/groups'
    | '/my-qrcodes'
    | '/projects'
    | '/sample'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/admin/customers'
    | '/ball-in-court/$workflowId'
    | '/group/$groupId'
    | '/procore/fetch'
    | '/procore/oauth-error'
    | '/procore/oauth-success'
    | '/procore/select-company'
    | '/project/$projectId'
    | '/qrcode/$qrcodeId'
    | '/task-signoff/$workflowId'
    | '/admin/db-backfill'
    | '/admin/ghl'
    | '/admin/nfc'
    | '/admin/online'
    | '/admin/stats'
    | '/storage/success'
    | '/verify-email/$token'
    | '/dashboard'
    | '/nfc/v1/$nfcId'
    | '/oauth/procore/callback'
    | '/oauth/procore/login'
    | '/tools/$tool/$itemId'
    | '/admin/customers/$companyId'
    | '/admin/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logged'
    | '/scannedQR'
    | '/checkout'
    | '/create-qr'
    | '/forgot-password'
    | '/groups'
    | '/my-qrcodes'
    | '/projects'
    | '/sample'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/ball-in-court/$workflowId'
    | '/group/$groupId'
    | '/procore/fetch'
    | '/procore/oauth-error'
    | '/procore/oauth-success'
    | '/procore/select-company'
    | '/project/$projectId'
    | '/qrcode/$qrcodeId'
    | '/task-signoff/$workflowId'
    | '/admin/db-backfill'
    | '/admin/ghl'
    | '/admin/nfc'
    | '/admin/online'
    | '/admin/stats'
    | '/storage/success'
    | '/verify-email/$token'
    | '/dashboard'
    | '/nfc/v1/$nfcId'
    | '/oauth/procore/callback'
    | '/oauth/procore/login'
    | '/tools/$tool/$itemId'
    | '/admin/customers/$companyId'
    | '/admin/customers'
  id:
    | '__root__'
    | '/'
    | '/logged'
    | '/scannedQR'
    | '/checkout'
    | '/create-qr'
    | '/forgot-password'
    | '/groups'
    | '/my-qrcodes'
    | '/projects'
    | '/sample'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/admin/customers'
    | '/ball-in-court/$workflowId'
    | '/group/$groupId'
    | '/procore/fetch'
    | '/procore/oauth-error'
    | '/procore/oauth-success'
    | '/procore/select-company'
    | '/project/$projectId'
    | '/qrcode/$qrcodeId'
    | '/task-signoff/$workflowId'
    | '/admin/db-backfill'
    | '/admin/ghl'
    | '/admin/nfc'
    | '/admin/online'
    | '/admin/stats'
    | '/storage/success'
    | '/verify-email/$token'
    | '/dashboard/'
    | '/nfc/v1/$nfcId'
    | '/oauth/procore/callback'
    | '/oauth/procore/login'
    | '/tools/$tool/$itemId'
    | '/admin/customers/$companyId'
    | '/admin/customers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggedRoute: typeof LoggedRoute
  ScannedQRRoute: typeof ScannedQRRoute
  CheckoutLazyRoute: typeof CheckoutLazyRoute
  CreateQrLazyRoute: typeof CreateQrLazyRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  GroupsLazyRoute: typeof GroupsLazyRoute
  MyQrcodesLazyRoute: typeof MyQrcodesLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  SampleLazyRoute: typeof SampleLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  VerifyEmailLazyRoute: typeof VerifyEmailLazyRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  BallInCourtWorkflowIdRoute: typeof BallInCourtWorkflowIdRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
  ProcoreFetchRoute: typeof ProcoreFetchRoute
  ProcoreOauthErrorRoute: typeof ProcoreOauthErrorRoute
  ProcoreOauthSuccessRoute: typeof ProcoreOauthSuccessRoute
  ProcoreSelectCompanyRoute: typeof ProcoreSelectCompanyRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  QrcodeQrcodeIdRoute: typeof QrcodeQrcodeIdRoute
  TaskSignoffWorkflowIdRoute: typeof TaskSignoffWorkflowIdRoute
  AdminDbBackfillLazyRoute: typeof AdminDbBackfillLazyRoute
  AdminGhlLazyRoute: typeof AdminGhlLazyRoute
  AdminNfcLazyRoute: typeof AdminNfcLazyRoute
  AdminOnlineLazyRoute: typeof AdminOnlineLazyRoute
  AdminStatsLazyRoute: typeof AdminStatsLazyRoute
  StorageSuccessLazyRoute: typeof StorageSuccessLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  NfcV1NfcIdRoute: typeof NfcV1NfcIdRoute
  OauthProcoreCallbackRoute: typeof OauthProcoreCallbackRoute
  OauthProcoreLoginRoute: typeof OauthProcoreLoginRoute
  ToolsToolItemIdRoute: typeof ToolsToolItemIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggedRoute: LoggedRoute,
  ScannedQRRoute: ScannedQRRoute,
  CheckoutLazyRoute: CheckoutLazyRoute,
  CreateQrLazyRoute: CreateQrLazyRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  GroupsLazyRoute: GroupsLazyRoute,
  MyQrcodesLazyRoute: MyQrcodesLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  SampleLazyRoute: SampleLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  VerifyEmailLazyRoute: VerifyEmailLazyRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  BallInCourtWorkflowIdRoute: BallInCourtWorkflowIdRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
  ProcoreFetchRoute: ProcoreFetchRoute,
  ProcoreOauthErrorRoute: ProcoreOauthErrorRoute,
  ProcoreOauthSuccessRoute: ProcoreOauthSuccessRoute,
  ProcoreSelectCompanyRoute: ProcoreSelectCompanyRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  QrcodeQrcodeIdRoute: QrcodeQrcodeIdRoute,
  TaskSignoffWorkflowIdRoute: TaskSignoffWorkflowIdRoute,
  AdminDbBackfillLazyRoute: AdminDbBackfillLazyRoute,
  AdminGhlLazyRoute: AdminGhlLazyRoute,
  AdminNfcLazyRoute: AdminNfcLazyRoute,
  AdminOnlineLazyRoute: AdminOnlineLazyRoute,
  AdminStatsLazyRoute: AdminStatsLazyRoute,
  StorageSuccessLazyRoute: StorageSuccessLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  NfcV1NfcIdRoute: NfcV1NfcIdRoute,
  OauthProcoreCallbackRoute: OauthProcoreCallbackRoute,
  OauthProcoreLoginRoute: OauthProcoreLoginRoute,
  ToolsToolItemIdRoute: ToolsToolItemIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logged",
        "/scannedQR",
        "/checkout",
        "/create-qr",
        "/forgot-password",
        "/groups",
        "/my-qrcodes",
        "/projects",
        "/sample",
        "/settings",
        "/signup",
        "/verify-email",
        "/admin/customers",
        "/ball-in-court/$workflowId",
        "/group/$groupId",
        "/procore/fetch",
        "/procore/oauth-error",
        "/procore/oauth-success",
        "/procore/select-company",
        "/project/$projectId",
        "/qrcode/$qrcodeId",
        "/task-signoff/$workflowId",
        "/admin/db-backfill",
        "/admin/ghl",
        "/admin/nfc",
        "/admin/online",
        "/admin/stats",
        "/storage/success",
        "/dashboard/",
        "/nfc/v1/$nfcId",
        "/oauth/procore/callback",
        "/oauth/procore/login",
        "/tools/$tool/$itemId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/logged": {
      "filePath": "logged.tsx"
    },
    "/scannedQR": {
      "filePath": "scannedQR.tsx"
    },
    "/checkout": {
      "filePath": "checkout.lazy.tsx"
    },
    "/create-qr": {
      "filePath": "create-qr.lazy.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.lazy.tsx"
    },
    "/groups": {
      "filePath": "groups.lazy.tsx"
    },
    "/my-qrcodes": {
      "filePath": "my-qrcodes.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/sample": {
      "filePath": "sample.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.lazy.tsx",
      "children": [
        "/verify-email/$token"
      ]
    },
    "/admin/customers": {
      "filePath": "admin.customers.tsx",
      "children": [
        "/admin/customers/$companyId",
        "/admin/customers/"
      ]
    },
    "/ball-in-court/$workflowId": {
      "filePath": "ball-in-court.$workflowId.tsx"
    },
    "/group/$groupId": {
      "filePath": "group.$groupId.tsx"
    },
    "/procore/fetch": {
      "filePath": "procore/fetch.tsx"
    },
    "/procore/oauth-error": {
      "filePath": "procore/oauth-error.tsx"
    },
    "/procore/oauth-success": {
      "filePath": "procore/oauth-success.tsx"
    },
    "/procore/select-company": {
      "filePath": "procore/select-company.tsx"
    },
    "/project/$projectId": {
      "filePath": "project.$projectId.tsx"
    },
    "/qrcode/$qrcodeId": {
      "filePath": "qrcode.$qrcodeId.tsx"
    },
    "/task-signoff/$workflowId": {
      "filePath": "task-signoff.$workflowId.tsx"
    },
    "/admin/db-backfill": {
      "filePath": "admin.db-backfill.lazy.tsx"
    },
    "/admin/ghl": {
      "filePath": "admin.ghl.lazy.tsx"
    },
    "/admin/nfc": {
      "filePath": "admin.nfc.lazy.tsx"
    },
    "/admin/online": {
      "filePath": "admin.online.lazy.tsx"
    },
    "/admin/stats": {
      "filePath": "admin.stats.lazy.tsx"
    },
    "/storage/success": {
      "filePath": "storage.success.lazy.tsx"
    },
    "/verify-email/$token": {
      "filePath": "verify-email.$token.lazy.tsx",
      "parent": "/verify-email"
    },
    "/dashboard/": {
      "filePath": "dashboard.index.tsx"
    },
    "/nfc/v1/$nfcId": {
      "filePath": "nfc.v1.$nfcId.tsx"
    },
    "/oauth/procore/callback": {
      "filePath": "oauth/procore/callback.tsx"
    },
    "/oauth/procore/login": {
      "filePath": "oauth/procore/login.tsx"
    },
    "/tools/$tool/$itemId": {
      "filePath": "tools.$tool.$itemId.tsx"
    },
    "/admin/customers/$companyId": {
      "filePath": "admin.customers.$companyId.lazy.tsx",
      "parent": "/admin/customers"
    },
    "/admin/customers/": {
      "filePath": "admin.customers.index.lazy.tsx",
      "parent": "/admin/customers"
    }
  }
}
ROUTE_MANIFEST_END */
